# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0008_auto_20161005_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon_url',
            field=models.CharField(default=None, max_length=511),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(0, '\u6682\u65e0'), (1, '\u7b80\u5355'), (2, '\u4e00\u822c'), (3, '\u56f0\u96be')]),
        ),
    ]
