# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0009_auto_20161006_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='coursedepartment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='coursetag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDepartment',
        ),
        migrations.DeleteModel(
            name='CourseTag',
        ),
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
